// This file will be generated by: pnpm openapi:generate
// Generated types from openapi/openapi.yaml

export interface HealthResponse {
  ok: boolean
  time: string
  db: 'up' | 'down'
}

export interface IncidentReportRequest {
  message: string
  severity: 'low' | 'medium' | 'high' | 'critical'
  context?: Record<string, any>
}

export interface IncidentReportResponse {
  id: string
  status: string
}

export interface TelemetryEventRequest {
  type: string
  payload?: Record<string, any>
}

export interface TelemetryEventResponse {
  id: string
  status: string
}

export interface DigestRenderRequest {
  days: number
}

export interface DigestRenderResponse {
  summary: string
  messageCount: number
}

export interface InboxActionRequest {
  action: 'archive' | 'route' | 'snooze'
  messageIds: string[]
}

export interface InboxActionResponse {
  processed: number
  status: string
}

export interface NDVIJobRequest {
  source: 'upload' | 'gdrive'
  acres?: number
}

export interface NDVIJobResponse {
  jobId: string
  status: 'pending' | 'processing' | 'completed' | 'failed'
  retryCount: number
}
