name: Frontend CI
on:
  pull_request:
    paths:
      - "apps/paulyops-ui/**"
      - ".github/workflows/frontend-ci.yml"
  push:
    branches: [ main ]
    paths:
      - "apps/paulyops-ui/**"
      - ".github/workflows/frontend-ci.yml"
jobs:
  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install
        run: pnpm i --frozen-lockfile
        working-directory: apps/paulyops-ui
      - name: Lint
        run: pnpm exec eslint .
        working-directory: apps/paulyops-ui
      - name: Build
        run: pnpm build
        working-directory: apps/paulyops-ui
